import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Maintenance from "./components/maintenance/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book now - Ajc Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><Maintenance /></body>
    </html>
  );
}
